[2025-07-09T23:01:40.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-09T23:01:40.968+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-09T23:01:39.599403+00:00 [queued]>
[2025-07-09T23:01:40.978+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-09T23:01:39.599403+00:00 [queued]>
[2025-07-09T23:01:40.979+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-09T23:01:40.993+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): list_files_in_s3_bucket> on 2025-07-09 23:01:39.599403+00:00
[2025-07-09T23:01:41.001+0000] {standard_task_runner.py:72} INFO - Started process 236117 to run task
[2025-07-09T23:01:41.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'list_s3_files', 'list_files_in_s3_bucket', 'manual__2025-07-09T23:01:39.599403+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/aws.py', '--cfg-path', '/tmp/tmpwbi5t73t']
[2025-07-09T23:01:41.008+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask list_files_in_s3_bucket
[2025-07-09T23:01:41.060+0000] {task_command.py:467} INFO - Running <TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-09T23:01:39.599403+00:00 [running]> on host dd8713d3b969
[2025-07-09T23:01:41.158+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='list_s3_files' AIRFLOW_CTX_TASK_ID='list_files_in_s3_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T23:01:39.599403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T23:01:39.599403+00:00'
[2025-07-09T23:01:41.159+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-09T23:01:41.193+0000] {base.py:84} INFO - Retrieving connection 'aws_s3'
[2025-07-09T23:01:41.194+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2025-07-09T23:01:59.213+0000] {logging_mixin.py:190} INFO - test output
[2025-07-09T23:01:59.941+0000] {logging_mixin.py:190} INFO - +---------+-----------------+------------+
|full_name|            email|phone_number|
+---------+-----------------+------------+
|    ahmed|  ahmed@gmail.com|123-456-7890|
|   monged| monged@gmail.com|123-456-7891|
|  youssef|youssef@gmail.com|123-456-7892|
|      ali|    ali@gmail.com|123-456-7893|
|    gamal|  gamal@gmail.com|123-456-7894|
+---------+-----------------+------------+
only showing top 5 rows
[2025-07-09T23:01:59.957+0000] {base.py:84} INFO - Retrieving connection 'AWS_PostgreSQL'
[2025-07-09T23:02:01.511+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-09T23:02:01.529+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-09T23:02:01.530+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=list_s3_files, task_id=list_files_in_s3_bucket, run_id=manual__2025-07-09T23:01:39.599403+00:00, execution_date=20250709T230139, start_date=20250709T230140, end_date=20250709T230201
[2025-07-09T23:02:02.959+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-09T23:02:02.980+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T23:02:02.982+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
