[2025-07-09T23:02:20.301+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-09T23:02:20.321+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-09T23:02:19.615243+00:00 [queued]>
[2025-07-09T23:02:20.331+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-09T23:02:19.615243+00:00 [queued]>
[2025-07-09T23:02:20.332+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-09T23:02:20.347+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): list_files_in_s3_bucket> on 2025-07-09 23:02:19.615243+00:00
[2025-07-09T23:02:20.354+0000] {standard_task_runner.py:72} INFO - Started process 236373 to run task
[2025-07-09T23:02:20.359+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'list_s3_files', 'list_files_in_s3_bucket', 'manual__2025-07-09T23:02:19.615243+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/aws.py', '--cfg-path', '/tmp/tmp4564j0bb']
[2025-07-09T23:02:20.361+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask list_files_in_s3_bucket
[2025-07-09T23:02:20.412+0000] {task_command.py:467} INFO - Running <TaskInstance: list_s3_files.list_files_in_s3_bucket manual__2025-07-09T23:02:19.615243+00:00 [running]> on host dd8713d3b969
[2025-07-09T23:02:20.508+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='list_s3_files' AIRFLOW_CTX_TASK_ID='list_files_in_s3_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T23:02:19.615243+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T23:02:19.615243+00:00'
[2025-07-09T23:02:20.509+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-09T23:02:20.536+0000] {base.py:84} INFO - Retrieving connection 'aws_s3'
[2025-07-09T23:02:20.537+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2025-07-09T23:02:38.584+0000] {logging_mixin.py:190} INFO - test output
[2025-07-09T23:02:39.373+0000] {logging_mixin.py:190} INFO - +---------+-----------------+------------+
|full_name|            email|phone_number|
+---------+-----------------+------------+
|    ahmed|  ahmed@gmail.com|123-456-7890|
|   monged| monged@gmail.com|123-456-7891|
|  youssef|youssef@gmail.com|123-456-7892|
|      ali|    ali@gmail.com|123-456-7893|
|    gamal|  gamal@gmail.com|123-456-7894|
+---------+-----------------+------------+
only showing top 5 rows
[2025-07-09T23:02:39.389+0000] {base.py:84} INFO - Retrieving connection 'AWS_PostgreSQL'
[2025-07-09T23:02:43.597+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-09T23:02:43.619+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-09T23:02:43.620+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=list_s3_files, task_id=list_files_in_s3_bucket, run_id=manual__2025-07-09T23:02:19.615243+00:00, execution_date=20250709T230219, start_date=20250709T230220, end_date=20250709T230243
[2025-07-09T23:02:43.874+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-09T23:02:43.896+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T23:02:43.897+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
